services:
  web:
    build: .
    image: ${image-version}
    container_name: advertiser_web
    command: uvicorn main:app --host 0.0.0.0 --port 8010
    volumes:
      - /opt/logs/advertiser_web:/app/logs/web:rw
    restart: on-failure
    network_mode: host

  celery_accounts_worker:
    image: ${image-version}
    container_name: advertiser_accounts_worker
    command: celery -A my_celery.main worker -Q update_accounts -n celery@update_accounts --loglevel=info --logfile=/app/logs/celery/account_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_balance_transfer_refund_worker:
    image: ${image-version}
    container_name: advertiser_balance_transfer_refund_worker
    command: celery -A my_celery.main worker -Q balance_transfer_refund -n celery@balance_transfer_refund --loglevel=info --logfile=/app/logs/celery/balance_transfer_refund_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_balance_transfer_recharge_worker:
    image: ${image-version}
    container_name: advertiser_balance_transfer_recharge_worker
    command: celery -A my_celery.main worker -Q balance_transfer_recharge -n celery@balance_transfer_recharge --loglevel=info --logfile=/app/logs/celery/balance_transfer_recharge_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_account_transfer_purse_worker:
    image: ${image-version}
    container_name: advertiser_account_transfer_purse_worker
    command: celery -A my_celery.main worker -Q account_transfer_purse -n celery@account_transfer_purse --loglevel=info --logfile=/app/logs/celery/account_transfer_purse_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_beat:
    image: ${image-version}
    container_name: advertiser_beat
    command: celery -A my_celery.main beat --loglevel=info --logfile=/app/logs/celery/beat.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_mapi_request_result_worker:
    image: ${image-version}
    container_name: advertiser_mapi_request_result_worker
    command: celery -A my_celery.main worker -Q mapi_request_result -n celery@mapi_request_result --loglevel=info --logfile=/app/logs/celery/mapi_request_result_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  celery_export_files_worker:
    image: ${image-version}
    container_name: advertiser_export_files_worker
    command: celery -A my_celery.main worker -Q export_files -n celery@export_files --loglevel=info --logfile=/app/logs/celery/export_file_worker.log
    restart: on-failure
    volumes:
      - /opt/logs/celery:/app/logs/celery:rw
    network_mode: host

  mirroring_crm_account:
    image: ${image-version}
    container_name: advertiser_mirroring_account
    command: python3 apps/common/mirroring_crm_account.py
    restart: on-failure
    volumes:
      - /opt/logs/mirroring_crm_account:/app/logs/mirroring_crm_account:rw
    network_mode: host
